apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-username: YWRtaW4=  # base64 encoded "admin"
  mongodb-root-password: cGFzc3dvcmQ=  # base64 encoded "password"
# immutable: true  
#Once a Secret or ConfigMap is marked as immutable, it is not possible to revert this change nor to mutate the contents of the data field. 
#You can only delete and recreate the Secret. Existing Pods maintain a mount point to the deleted Secret
#it is recommended to recreate these pods.